repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.292
    hooks:
      - id: ruff
        args: [--fix]
      # Temporarily disabled - formatting applied manually
      # - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: [types-PyYAML, types-requests, pydantic]
        args: [--config-file, pyproject.toml]
        files: ^(src/api/|src/assets/|src/utils/config\.py|src/utils/types\.py).*\.py$


  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ["tests/production/test_api_endpoints.py::TestHealthEndpoints", "tests/unit/test_config.py", "tests/unit/test_logging.py", "tests/unit/test_asset_manager.py", "--tb=short", "-q", "--maxfail=3"]
