apiVersion: apps/v1
kind: Deployment
metadata:
  name: ll3m-api
  namespace: ll3m
  labels:
    app: ll3m-api
    component: backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ll3m-api
  template:
    metadata:
      labels:
        app: ll3m-api
    spec:
      containers:
      - name: ll3m-api
        image: ll3m/api:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: ll3m-secrets
              key: database-url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ll3m-secrets
              key: secret-key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ll3m-secrets
              key: openai-api-key
        envFrom:
        - configMapRef:
            name: ll3m-api-config
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /api/v1/health/live
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/health/ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: asset-storage
          mountPath: /app/storage
      volumes:
      - name: asset-storage
        persistentVolumeClaim:
          claimName: asset-storage-pvc

