apiVersion: apps/v1
kind: Deployment
metadata:
  name: ll3m-web
  namespace: ll3m
  labels:
    app: ll3m-web
    component: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: ll3m-web
  template:
    metadata:
      labels:
        app: ll3m-web
    spec:
      containers:
      - name: ll3m-web
        image: ll3m/web:latest
        ports:
        - containerPort: 3000
          name: http
        envFrom:
        - configMapRef:
            name: ll3m-web-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

