agents:
  planner:
    model: "gpt-4"
    temperature: 0.7
    max_tokens: 1000
    
  retrieval:
    model: "gpt-4"
    temperature: 0.3
    max_tokens: 1500
    
  coding:
    model: "gpt-4"
    temperature: 0.3
    max_tokens: 2000
    
  critic:
    model: "gpt-4-vision-preview"
    temperature: 0.5
    max_tokens: 1500
    
  verification:
    model: "gpt-4"
    temperature: 0.3
    max_tokens: 1000